export const AFFILIATE_MOMENTS = {
  business: [
    {
      id: 'domain',
      title: 'Domain Check',
      where: 'Results Page',
      trigger: 'Winner announced',
      type: 'domain-check',
      headline: 'Is the domain available?',
      subtext: 'Check availability for your winning name across .com, .io, and more — before someone else grabs it.',
      partner: 'Namecheap',
      partnerTag: 'Domain Registrar',
      cta: 'Check domain →',
      emoji: '*',
    },
    {
      id: 'trademark',
      title: 'Trademark Search',
      where: 'Results Page',
      trigger: 'After shortlist view',
      type: 'trademark',
      headline: 'Can you legally own this name?',
      subtext: 'Professional trademark search catches phonetic matches and conflicts the free search misses. Catch problems before you invest in branding.',
      partner: 'LegalZoom',
      partnerTag: 'Trademark Search',
      cta: 'Full search via LegalZoom →',
      emoji: '*',
    },
    {
      id: 'logo',
      title: 'Logo Design',
      where: 'Results Page',
      trigger: 'After winner announced',
      type: 'logo',
      headline: 'Your name is chosen. Now build the brand.',
      subtext: 'AI-generated logos in minutes (Looka) or a full design contest with multiple concepts (99designs). Coverage at every price point.',
      partner: 'Looka / 99designs',
      partnerTag: 'Brand Design',
      cta: 'Create on Looka →',
      emoji: '*',
    },
    {
      id: 'incorporation',
      title: 'Business Registration',
      where: 'Results Page',
      trigger: 'Winner announced for Company Name or Rebrand',
      type: 'registration',
      headline: 'Now make it official',
      subtext: 'You have a winning name — register your LLC or corporation before someone else does. LegalZoom handles the paperwork.',
      partner: 'LegalZoom',
      partnerTag: 'Business Formation',
      cta: 'Register your business →',
      emoji: '*',
    },
    {
      id: 'catchword-services',
      title: 'Catchword Professional Naming',
      where: 'Results Page — Post-Vote Reflection',
      trigger: 'Business user selects "second thoughts" or "still not sure"',
      type: 'own-service',
      headline: 'Need expert help? Let Catchword name it for you.',
      subtext: 'Your contest data — brief, submissions, votes — becomes the starting point for Catchword\'s professional naming team. 25+ years of experience, 3,000+ brands named.',
      partner: 'Catchword Branding',
      partnerTag: 'Own Service',
      cta: 'Explore Catchword Services →',
      emoji: '*',
    },
  ],

  team: [
    {
      id: 'merch',
      title: 'Team Merchandise',
      where: 'Results Page',
      trigger: 'Winner announced',
      type: 'merch',
      headline: 'Make it official with merch.',
      subtext: 'Print your new team name on jerseys, hoodies, and gear. No minimums.',
      partner: 'Printful',
      partnerTag: 'Custom Merchandise',
      cta: 'Design team merch →',
      emoji: '*',
    },
    {
      id: 'logo-team',
      title: 'Team Logo',
      where: 'Results Page',
      trigger: 'After winner announced',
      type: 'logo',
      headline: 'Every great team name needs a great logo.',
      subtext: 'Work with a designer to create a logo that matches your new team identity. Multiple concepts, unlimited revisions.',
      partner: '99designs',
      partnerTag: 'Brand Design',
      cta: 'Get a team logo →',
      emoji: '*',
    },
    {
      id: 'website',
      title: 'Team Website',
      where: 'Results Page',
      trigger: 'After winner announced',
      type: 'website',
      headline: 'Claim your team\'s home online.',
      subtext: 'Build a simple team website with schedules, roster, and news. No coding required.',
      partner: 'Squarespace',
      partnerTag: 'Website Builder',
      cta: 'Build your team site →',
      emoji: '*',
    },
    {
      id: 'domain-team',
      title: 'Domain Check',
      where: 'Results Page',
      trigger: 'Winner announced',
      type: 'domain-check',
      headline: 'Secure your team\'s domain.',
      subtext: 'Lock in the domain for your new team name before someone else does.',
      partner: 'Namecheap',
      partnerTag: 'Domain Registrar',
      cta: 'Check domain →',
      emoji: '*',
    },
  ],

  personal: [
    {
      id: 'announcement',
      title: 'Birth Announcement',
      where: 'Results Page',
      trigger: 'Winner announced — baby name',
      type: 'announcement',
      headline: 'Share the name with the world.',
      subtext: 'Premium birth announcement cards, printed and shipped. The name you chose together, beautifully presented.',
      partner: 'Artifact Uprising',
      partnerTag: 'Custom Cards & Prints',
      cta: 'Design announcements →',
      emoji: '*',
    },
    {
      id: 'gift',
      title: 'Personalised Gift',
      where: 'Results Page',
      trigger: 'After winner announced',
      type: 'gift',
      headline: 'Celebrate the name.',
      subtext: 'Personalised gifts featuring the chosen name — perfect for new babies, pets, or homes.',
      partner: 'Etsy',
      partnerTag: 'Personalised Gifts',
      cta: 'Shop personalised gifts →',
      emoji: '*',
    },
    {
      id: 'name-book',
      title: 'Baby Name Guide',
      where: 'Brief Builder',
      trigger: 'Contest type: Baby Name',
      type: 'resource',
      headline: 'Need more inspiration?',
      subtext: 'Explore the most comprehensive baby name book — meanings, origins, and trends.',
      partner: 'Amazon',
      partnerTag: 'Book',
      cta: 'Browse baby name books →',
      emoji: '*',
    },
    {
      id: 'pet-id',
      title: 'Pet ID Tag',
      where: 'Results Page',
      trigger: 'Winner announced — pet name',
      type: 'merch',
      headline: 'Make it official for your pet.',
      subtext: 'Custom ID tags and personalised accessories with your pet\'s new name.',
      partner: 'Chewy',
      partnerTag: 'Pet Accessories',
      cta: 'Get a custom ID tag →',
      emoji: '*',
    },
  ],
};

export const AFFILIATE_PLAN_LABEL = {
  business: 'Business Contest',
  team: 'Group / Team Contest',
  personal: 'Personal Contest',
};
